baseURL = "http://example.com/"
disqusShortname = "username"
googleAnalytics = ""
languageCode = "en-us"
theme = "minimal"
title = "Minimal"
[[menu.icon]]
name = "envelope-o"
url = "mailto:me@example.com"
weight = 1
[[menu.icon]]
name = "github"
url = "https://github.com/username/"
weight = 2
[[menu.icon]]
name = "twitter"
url = "https://twitter.com/username/"
weight = 3
[[menu.icon]]
name = "linkedin"
url = "https://www.linkedin.com/in/username/"
weight = 4
[[menu.icon]]
name = "stack-overflow"
url = "https://www.stackoverflow.com/username/"
weight = 5
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2
[[menu.main]]
name = "Projects"
url = "/project/"
weight = 3
[params]
accent = "red"
author = "Kenneth Dée - journalist"
backgroundColor = "white"
description = "Personal blog theme powered by Hugo"
font = "Raleway"
githubUsername = "#"
highlight = true
highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
highlightStyle = "solarized-dark"
showBorder = true
